### ISSUE TITLE
Fatal error: Uncaught exception 'Blockchain\Exception\ApiError' with message 'Not found'

### ISSUE THREAD

**Issue by mctracker** [blockchain/api-v1-client-php#40]
Here's the code:

```
$Blockchain = new \Blockchain\Blockchain();
$Blockchain->setServiceUrl("http://localhost:3000");
$Blockchain->Wallet->credentials('myid', 'mypass');
$stats = $Blockchain->Stats->get();
var_dump($stats);
$balance = $Blockchain->Wallet->getBalance();
var_dump($balance);
```

And I got following exception message:

```
Fatal error: Uncaught exception 'Blockchain\Exception\ApiError' with message 'No
t found' in C:\xampp\htdocs\test\Blockchain\Blockchain.php:114
Stack trace:
#0 C:\xampp\htdocs\test\Blockchain\Wallet\Wallet.php(47): Blockchain\Blockchain-
>post('merchant/16d72a...', Array)
#1 C:\xampp\htdocs\test\Blockchain\Wallet\Wallet.php(55): Blockchain\Wallet\Wall
et->call('balance')
#2 C:\xampp\htdocs\test\wallet.php(26): Blockchain\Wallet\Wallet->getBalance()
#3 {main}
  thrown in C:\xampp\htdocs\test\Blockchain\Blockchain.php on line 114
```

Why does this happen?

**Comment by Montymort** [comment]
Hi, 
I have encountered the same problem. After contacting the support and a few tests I think I have found the cause for this. Regarding the instructions you should set your service url like "http://localhost:3000", but you need to enter a slash at the end like "http://localhost:3000/". The Library connects to "http://localhost:3000merchant/..." instead of "http://localhost:3000/merchant/...". This is a silly solution so I changed the setServiceUrl function to add a slash if missing. I also added a pull request for this. Maybe this will help you.
kind regards,
Montymort

**Comment by mctracker** [comment]
@Montymort, hey, thanks for answering that issue! If I deal with this api again I'll use your hint. Regards!

**Comment by denis-dima** [comment]
Try this: $Blockchain->setServiceUrl("http://localhost:3000/"); add "/"
